CREATE TABLE snippets (
  id VARCHAR(255) UNIQUE NOT NULL,
  code TEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
